### ISSUE TITLE
Access calculateTextDimensions

### ISSUE THREAD

**Issue by derBingle** [chunyenHuang/hummusRecipe#10]
Thanks for the repo, it's been a big help in understanding Hummus! 

I need to access `calculateTextDimensions()` in order to set text precisely above the line below — is there a way to access it from hummusRecipe?

**Comment by chunyenHuang** [comment]
The cheating way is to access Hummus pdfWriter through `.writer`.
https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/Recipe.js#L46
Then you can use the any property from the pdfWriter.

**Comment by derBingle** [comment]
Awesome, thanks @chunyenHuang!
