### ISSUE TITLE
Add CMYK & Gray colorspace usage

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#100]
The hummus library supports CMYK and Gray color space definitions for PDF. Hummus-recipe currently just uses RGB.

All the current interfaces which allow color specifications with a hex value or an array will be affected. So users would be able to enter the following:

```
HEX 	->  color: #rrggbb, #ccmmyykk, #gg, 
ARRAY	->  [red,green,blue], [cyan,magenta,yellow,black],  [gray] 
```
The array values are expected to be numbers 0-255.

**Comment by chunyenHuang** [comment]
Added in `1.8.7`

**Comment by chunyenHuang** [comment]
https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/color.js
