### ISSUE TITLE
Recipe cannot open password protected file

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#109]
HummusJS has the ability to create/open password encrypted file, but Recipe has blocked the needed parameters to supply to createWriter and createWriterToModify. Recipe does allow the initially opened file to be encrypted after the fact of initial creation via 'encrypt' interface, but that effectively is a post processing effect.  So even though one can create an encrypted file using Recipe, that same file cannot be subsequently modified via Recipe.

**Comment by shaehn** [comment]
Ok, nevermind.... I seem to have run into an incorrect coding. It does behave the same.

**Comment by chunyenHuang** [comment]
`hummus-recipe@1.8.9`

**Comment by shaehn** [comment]
Thanks John!
