### ISSUE TITLE
line drawn after editPage does not appear in document

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#123]
When attempting to edit a page of an existing document, The first segment of a line never gets drawn. (In example below, segment delineated by the coordinates [180,0],[180,500] not drawn)

```javascript
const src = path.join(__dirname, 'materials/blank.pdf');
const output = path.join(__dirname, 'output/lineTest.pdf');
const recipe = new HummusRecipe(src, output);

recipe
    .editPage(1)
    .line([[180,0],[180,500],[200,400]],{stroke:"#ff00ff",lineWidth:.5})
    .endPage()
    .endPDF();
```

Whereas creating a new page using the same line command works as expected.

``` javascript
const output = path.join(__dirname, 'output/lineTest.pdf');
const recipe = new HummusRecipe('new', output);

recipe
    .createPage('letter-size')
    .line([[180,0],[180,500],[200,400]],{stroke:"#ff00ff",lineWidth:.5})
    .endPage()
    .endPDF();
```

**Comment by VinnyV88** [comment]
Having the same issue. I'm trying to draw several lines, the first line never appears. So, as a workaround, I just draw a dummy line and then any subsequent lines appear. This should be fixed  though.

`    pdfDoc
    .editPage(1)
    .line([[.1, .1], [.1, .1]] , {color: "#000000", lineWidth: .1}) // for some reason, the first line doesn't print, this is a dummy line
    .line([[x, yLastLine1], [m, yLastLine1]] , {color: "#000000", lineWidth: .5})
    .line([[x, yLastLine2], [m, yLastLine2]] , {color: "#000000", lineWidth: .5})
    .line([[x, yLastLine3], [m, yLastLine3]] , {color: "#000000", lineWidth: .5})
    .text(beneMsg, 20, yBeneMsg, { fontSize: 10, color:'000000', font: 'Calibri', bold: true } )
    .endPage()
    // end and save
    .endPDF((outBuffer) => {
        buffArray[otherLastLine.page - 1] = outBuffer;
    });
`

**Comment by shaehn** [comment]
I think this may be a hummus problem when using hummus.PDFPageModifier as opposed to hummus.createWriter. There is some state issue that is not set up when editing that drops the first coordinates on the floor and then uses the 2nd coordinates for the PDF 'move' command.

In any case, I have figured out a hack that I can apply to page.js (set up a this.editingPage boolean) and then test for in 'line' to force out the first segment.
