### ISSUE TITLE
Background of page

### ISSUE THREAD

**Issue by j8** [chunyenHuang/hummusRecipe#13]
I need to create different background for each page? What is the way to do this?

**Comment by chunyenHuang** [comment]
I think the easiest way is to create a rectangle at beginning, something like
```
.rectangle(0, 0, pageWidth, pageHeight, {
    color: [255, 0, 0],
    opacity: 0.2    
})
```
and then you can add you stuff on top of it.

**Comment by chunyenHuang** [comment]
@j8 Do you still need help for this?
