### ISSUE TITLE
Expand library color system concepts (to allow Pantone colors)

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#134]
John, I already have a working version of what is described below. The question to you is how do I/we go about updating the documentation to explain it to users? I will create a PR request once PR #133 gets integrated.

### New hummus-recipe library color system concepts:

    1. Named colors (eg. red, blue, pink, etc.), with new option 'colorName'
    2. A new interface to define colors (called chroma)
    3. PercentColor format, aimed at easier CMYK values (eg. %0,100,0,0)
    4. A fourth colorspace, called 'separation' which will 
       allow users to specify Pantone colors in their PDF's.
    
The named colors will have a hex or percentage value assigned to them and will be assciated with one of the 4 colorspaces, rgb, cmyk, gray, or separation, which effectively allows the same named color to be specified in any of the colorspaces.

The library has a minimal predefined set of named colors as follows:
```
    'rgb': {
        'red'    : 'ff0000',
        'green'  : '00ff00',
        'blue'   : '0000ff',
    },
    'cmyk': {
        'cyan'   : 'ff000000',
        'magenta': '00ff0000',
        'yellow' : '0000ff00',
        'black'  : '000000ff'
    },
    'gray': {
        'white'  : 'ff',
        'black'  : '00'
    },
    'separation' : {
        'cyan'   : 'ff000000',
        'magenta': '00ff0000',
        'yellow' : '0000ff00',
        'black'  : '000000ff'
    }
```
The 'separation' color space values are special in that they represent the alternate colorspace to be used when the named color cannot be rendered directly by a conforming PDF reader. Note that the the alternate colorspace values may come from rgb, cmyk, or gray colorspaces. (The values in the example above are from the cmyk colorspace)

There is a new interface called 'chroma' which will allow a user to define their own color names along with their associated values and colorspace. It also allows reading a JSON file containing a set of predefined colors.

    recipe.chroma(name, value, colorspace='')
    
where
```
    name  {string}, 
          is the name to be associated with the given color value
	  or the special flag '!load'.
	  
    value {string|number[]}
          the color value to be associated with the given name. The format may be
	  either HexColor or PercentColor string, or a DecimalColor array. When
	  '!load' is specified as the color name, this value should be the path to
	  JSON file holding a set of colors to be merged into the existing known
	  colors.

    colorspace {string} (optional)
          one of the following: 'rgb', 'cmyk', 'gray', 'separation'.
	  When missing, the given value is used to determine the actual colorspace
	  from either rgb, cmyk, or gray. This value is not optional for the
	  'separation' colorspace.
```
Here are some example usages:

```javascript
  recipe
     // These are added to rgb colorspace
    .chroma('aqua', '#00ffff')
    .chroma('underline', '#FF000' )
    .chroma('yellow', [255,255,0])
    
    // These are added to cmyk colorspace
    .chroma('purple', '%29,52,0,34')
    .chroma('red', '#00ffff00')
    
    // These are added to separation colorspace
    .chroma('PANTONE 1505 C', '%0,56,90,0', 'separation' )
    .chroma('PANTONE 3537 C', '%100,14,99,65', 'separation')
    
    // Now use defined colors
    .text('Aqua', 100, 100, {color:'aqua'})
    .text('Purple', 100, 120, {color: 'purple'})
    .circle(200, 100, 20, {fill: 'yellow', stroke: 'red'})
    .circle(300, 200, 20, {color: 'PANTONE 3537 C'})
```    
Note that colors can also be defined in the other interfaces via the 'colorName' option.

As an example:
```javascript
  recipe
     .text('Define Gold Here', 100, 220, {color: '#ff9900', colorName: 'gold'})
     .text('Using Gold Here', 100, 300, {color: 'gold'})
     .text('Separation color orange', 100, 490, 
         {color: [255,69,0], colorName: 'orange', colorspace: 'separation'})
```
When wanting to load a file full of predefined colors, which will be merged with the existing colorspaces, do the following:
```javascript
  recipe
    .chroma('!load', '/path/to/file/containing/color/definitions.JSON')
```    
The layout of the file has to put the colors in one of the predefined colorspaces;
rgb, cmyk, gray, or separation. Files may contain one or more colorspaces. Following
is an example file contents for some predefined rgb and cmyk colors.
```
    { 
      "rgb": {
        "aliceblue": "f0f8ff",
        "antiquewhite": "faebd7",
        "aqua": "00ffff",
        "aquamarine": "7fffd4",
        "azure": "f0ffff"
	}
      "cmyk": {
        "yellow" : "%0,0,100,0",
        "black" : "#000000ff"
      }
    }
```    
Note that the associated color values may be in either HexColor or PercentColor
strings. (Here the '#' character used to introduce a HexColor is optional)

**Comment by shaehn** [comment]
Yay......., thanks for the merge! I can begin incorporating it today.

**Comment by JulianNicolas** [comment]
Hello shaehn, this is an awesome feature.
I am very excited to be able to make it work 

Anyway I have a problem trying to get it to work.
I am trying with your example as it is 
When I add this lines .. 
"
    .chroma('PANTONE 3537 C', '%100,14,99,65', 'separation')
    .circle(300, 200, 20, {color: 'PANTONE 3537 C'})
"
for example I get this circle drawn with RGB values "23 119 209", some kind of blue. 
I will attach the resultant pdf file. 

am I doing something wrong?

thank you in advance!

PD: awesome feature!!

[output.pdf](https://github.com/chunyenHuang/hummusRecipe/files/4867496/output.pdf)

**Comment by shaehn** [comment]
Looks like this broke when text justification was implemented. I will submit a new issue.

**Comment by JulianNicolas** [comment]
Thank you very much.
I appreciate it
