### ISSUE TITLE
Get PDF information

### ISSUE THREAD

**Issue by federico-solveit** [chunyenHuang/hummusRecipe#140]
Hi. Thanks for creating such an amazing library.
I could set the pdf information (eg. subject, title) using info(), but can I get that information from an existing pdf?

**Comment by shaehn** [comment]
Have you tried the getPageInfo() interface?

**Comment by federico-solveit** [comment]
Thanks for kind reply @shaehn, I've just tried but it doesn't seem to work. I set the subject to 'subject'.

InfoDictionary {
  trapped: 2,
  producer: '',
  creator: '',
  keywords: '',
  subject: '',
  author: '',
  title: ''
}

**Comment by shaehn** [comment]
@federico-solveit  I did some rummaging around and I don't see a hummus-recipe interface that will do what you are asking. It is geared toward writing out new data to output, copying the previous data along with it. So I guess I would ask what problem are you trying to solve, or what do you want to do with the existing data?

**Comment by federico-solveit** [comment]
Tbh, I am now creating a microservice to stamp pdf documents, I used this library to do so. 
And it also involves getting the title from the pdf info. I could set it using info() as said, but I am just wondering if I have to find another library to get the title.
Thanks!

**Comment by shaehn** [comment]
You can do it directly using hummus, which is the underlying library that hummus-recipe uses so you don't have to get another library. It is already present. Look here for hints on how to do it.
[https://github.com/galkahana/HummusJS/issues/27](url)

**Comment by federico-solveit** [comment]
Thanks so much for taking time, @shaehn! I was using HummusRecipe since it is way more convenient than HummusJS, and so I've wrote some code using that library. Should I migrate back to HummusJS to do this?

**Comment by shaehn** [comment]
I use both libraries interchangeably. hummus-recipe has higher level concepts to simplify access, However, sometimes there are unique situations that require getting into the nether regions of hummus.

**Comment by chunyenHuang** [comment]
https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/info.js#L5

**Comment by federico-solveit** [comment]
Hi @chunyenHuang! I was looking for a feature to get the pdf information (eg. title, subject), but I think the link you provided is about setting the pdf information.
Could you explain more about it if I misunderstood something?
Thanks.

**Comment by federico-solveit** [comment]
> https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/info.js#L5

**Comment by chunyenHuang** [comment]
> > https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/info.js#L5
> 
> Hi @chunyenHuang! I was looking for a feature to get the pdf information (eg. title, subject), but I think the link you provided is about setting the pdf information.
> Could you explain more about it if I misunderstood something?
> Thanks.

Well, I just take a look at the code, it seems to me that the info is written at the end. You may split the `_writeInfo` function to `_readInfo` and execute it at beginning.

```javascript
exports._readInfo = function _readInfo(){
    const options = this.toWriteInfo_ || {};
    const copyFrom = this.isBufferSrc ? new hummus.PDFRStreamForBuffer(this.src) : this.src;
    const copyCtx = this.writer.createPDFCopyingContext(copyFrom, options);
    const infoDict = copyCtx.getSourceDocumentParser().queryDictionaryObject(
        copyCtx.getSourceDocumentParser().getTrailer(), 'Info'
    );
    return (infoDict && infoDict.toJSObject) ? infoDict.toJSObject() : null;
};
```

```javascript
console.log(recipe._readInfo())
{ Author:
   PDFLiteralString {
     value:
      'yo manMon Sep 30 2019 10:24:47 GMT-0700 (Pacific Daylight Time)' },
  CreationDate: PDFLiteralString { value: 'D:20171018135940-07\'00\'' },
  Creator:
   PDFLiteralString {
     value:
      'Hummus-Recipe (https://github.com/chunyenHuang/hummusRecipe)' },
  Keywords: PDFLiteralString { value: 'hummus,js,??,234' },
  ModDate: PDFLiteralString { value: 'D:20190930102447-07\'00\'' },
  Producer:
   PDFLiteralString { value: 'PDFHummus (https://github.com/galkahana/HummusJS)' },
  Subject: PDFLiteralString { value: 'Blank PDF' },
  Title: PDFLiteralString { value: 'Hello World' },
  'source-Creator':
   PDFLiteralString {
     value:
      'Hummus-Recipe (https://github.com/chunyenHuang/hummusRecipe)' },
  'source-ModDate': PDFLiteralString { value: 'D:20171018135940-07\'00\'' },
  'source-Producer':
   PDFLiteralString { value: 'PDFHummus (https://github.com/galkahana/HummusJS)' } }
```
