### ISSUE TITLE
Write unicode text to PDF

### ISSUE THREAD

**Issue by federico-solveit** [chunyenHuang/hummusRecipe#143]
Is it possible to write Unicode text(ex. Chinese or Russian) to an existing pdf? I used text() function to write non-English text but I am getting some squares(􀀀) from the result pdf.

**Comment by shaehn** [comment]
Yes it is possible. The problem you are seeing is that the text is not being displayed with a font that has those characters.  See [https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/font.js](url)

**Comment by federico-solveit** [comment]
Thanks @shaehn! It's just what I was looking for. I'd like to share the font I used since some fonts only worked for one language but not for other languages. https://github.com/adobe-fonts/source-han-sans. It worked for both Chinese and Russian language out of the box.
