### ISSUE TITLE
Letter-spacing for text element

### ISSUE THREAD

**Issue by Chrisjow** [chunyenHuang/hummusRecipe#145]
Hi,

I am editing a PDF, adding a new text element with a code like below

`.text('Welcome to Hummus-Recipe', 'center', 250, {
        color: '066099',
        fontSize: 30,
        bold: true,
        font: 'Helvatica',
        align: 'center center',
        opacity: 0.8,
        rotation: 180
    })`

I would like to apply a letter-spacing effect to this text, to fit with the field: 
![image](https://user-images.githubusercontent.com/16521527/66921390-5dd1d680-f025-11e9-933d-4c22b09fe134.png)

Is it possible?

Thanks.

**Comment by shaehn** [comment]
So if you are asking if you can do .text('Code postal |__|__|__|__|__|', x, y), then I would say yes. If it is something else, then a better example is needed.

**Comment by Chrisjow** [comment]
I have a document which is an empty form, with some fields like 
![image](https://user-images.githubusercontent.com/16521527/67110788-cfe81e00-f1d3-11e9-9985-c72c744bbc99.png)

I am using Hummus in order to fill out this form. So, when I need to fill out fields like "Code postal", I need to apply a specific letter-spacing to my text in order to have one digit per box.

example:
Code postal |_7_|_5_|_0_|_1_|_0_|

**Comment by shaehn** [comment]
As it currently exists, hummus-recipe does not have a character spacing setting for given text. You would have to split up the digits as separate items and position them accordingly into the spaces you have described.

**Comment by shaehn** [comment]
Or as an alternative, hide the empty field markers where the numbers are going to be placed with a filled rectangle matching the color of the background and overlay the numbers on top of the rectangle so you won't have to worry about spacing.

**Comment by Chrisjow** [comment]
I split up the digits as different elements to do what I want.

Thanks for your help
