### ISSUE TITLE
Kerning

### ISSUE THREAD

**Issue by tsabbay** [chunyenHuang/hummusRecipe#147]
Hi Guys,
Did anyone was able to work with letter spacing(kerning) and can suggest how?

**Comment by shaehn** [comment]
Ok, to be clear, letter spacing (aka, tracking) is not kerning. Most fonts already have kerning for specific letter pairs.  I have worked on adding a new text attribute called charSpace which provides a numeric value for the amount of space to be placed between letters in a word, where 1 = 1/72 of inch. Here is a picture of the results. Is this what you are looking for?

![image](https://user-images.githubusercontent.com/13596544/70954588-dfe97600-203b-11ea-8fef-d3e713e8d42c.png)

**Comment by shaehn** [comment]
fixed in release 1.9.1
