### ISSUE TITLE
Truncate text

### ISSUE THREAD

**Issue by Chrisjow** [chunyenHuang/hummusRecipe#149]
Hi, 

Is there a way to truncate text if its width is higher than a particular amount?

I thought that the textbox > width parameter could be what I wanted but it's not.

Thanks.
Christophe

**Comment by shaehn** [comment]
In reference to issue #52, the closest I could come to that was something like the following, where I have added the textBox option called 'wrap', setting it to false:
```javascript
.text(`minHeight: ${h}\nBox will not collapse when not\nenough text to fill. It will auto grow when text exceeds minHeight.`, 150, 625, {
    color: '#000000',
    size: 9,
    textBox: {
        width: 100,
        minHeight: h,
        wrap: false,
        textAlign: 'center',
        style: {
            stroke: '#000000',
            lineWidth:.5,
        }
    }
})
```

When wrap is true, the following picture is created:
![image](https://user-images.githubusercontent.com/13596544/67884302-f97e3f00-fb1b-11e9-920b-9175a578f0d1.png)

When wrap is false, the following picture is created:
![image](https://user-images.githubusercontent.com/13596544/67884359-16b30d80-fb1c-11e9-8ec9-7234f279633b.png)

In words, this is what is happening when wrap is set to false. The algorithm keeps looking to see if the next word will fit on the line, if it won't fit, it flushes the remainder of the text until it encounters another newline character. So it sort of does what is wanted, but it will not break off in the middle of a word and does not put in an ellipsis (...) to let you know a truncation has occurred. You just get missing text. If this is satisfactory, as you can see I have it implemented.

**Comment by Chrisjow** [comment]
I am not sure I understood what to do to get this image :
![image](https://user-images.githubusercontent.com/16521527/67934408-2556fe80-fbc8-11e9-8d38-bb23782d8009.png)

I tried the code you gave (with wrap = false) and it does not work for me:
![image](https://user-images.githubusercontent.com/16521527/67934502-4d466200-fbc8-11e9-9598-24a5517c8370.png)

**Comment by shaehn** [comment]
It does not work for you because the code is not checked into the GitHub repository yet. It only exists on my machine. I am showing two different ways for final results and wanted to know what is preferable; the first one with the missing text, or the second one where the text gets clipped in the middle of a word.

**Comment by Chrisjow** [comment]
Oh okay!

In my case, I prefer the first one (only full words displayed, or at least full letters).

**Comment by shaehn** [comment]
The final solution has been checked in so you can now try it out. The wrap option can take on a string value ('auto', 'clip', 'trim', 'ellipsis'), or a boolean value (true, which is equivalent to 'auto' and false, which is equivalent to 'ellipsis'). 'Clip' will slice the word that won't fit right at the text boundary. 'Trim' removes the words that won't fit on the line. 'Ellipse' puts '...' at the end of the line that has more text than can fit in the box.

**Comment by Chrisjow** [comment]
Thanks a lot @shaehn!

Just integrated this new feature and it is exactly what I needed.
