### ISSUE TITLE
oldInfo.Author.toText is not a function

### ISSUE THREAD

**Issue by chadkirby** [chunyenHuang/hummusRecipe#15]
I'm running into an error when I try to add an annotation to an existing PDF that has Title or Author metadata. For example, [this file](https://github.com/chunyenHuang/hummusRecipe/files/1476391/test.pdf).

This code throws on `endPDF()` because it can't copy `infoDictionary` entries from the source document.
```
  const pdfDoc = new HummusRecipe(`${__dirname}/data/test.pdf`, `${__dirname}/data/test_out.pdf`);
  pdfDoc.editPage(page).rectangle(100, 100, 200, 200).endPage();
  pdfDoc.endPDF();
```

**Comment by chunyenHuang** [comment]
Thanks for reporting this issue. It's because the source pdf file writes the information in Thanks for reporting this issue. It's because the source pdf file writes the information in `indirectObjectReference` which is not handled in the current version.

It is fixed in version `1.4.2`

**Comment by chunyenHuang** [comment]
@chadkirby Do you still have issue with this?

**Comment by chadkirby** [comment]
No, I've been using v1.4.3 for a couple months, and it's been pretty reliable.

**Comment by chunyenHuang** [comment]
cool. I will close this ticket then.
