### ISSUE TITLE
Loop Editing

### ISSUE THREAD

**Issue by Ph4raoh** [chunyenHuang/hummusRecipe#155]
**Is it possible to edit the same pdf just by changing the position with a for? something like that:**

`const HummusRecipe = require('hummus-recipe');
const pdfDoc = new HummusRecipe(
  "input.pdf",
  "output.pdf"
);

position = 250;
for (x = 0; x < 2; x++) {
  pdfDoc.editPage(1)

    .text('Add some texts to an existing pdf file', 150, position)

  position +=  50;

}

pdfDoc.endPage();

pdfDoc.endPDF();`

**Comment by shaehn** [comment]
yes.
