### ISSUE TITLE
Create new page it text is large to fit in one page?

### ISSUE THREAD

**Issue by hugodion** [chunyenHuang/hummusRecipe#161]
Hi!
How can we force the creation of a new page automatically if the content of a text is too large to fit into one page?
Thanks in advance!

**Comment by shaehn** [comment]
Currently, text objects are just that, objects that go on a page like the graphic elements. There isn't a concept of 'overflow' to get what you want.

**Comment by hugodion** [comment]
Ok thanks for the reply !

**Comment by shaehn** [comment]
@hugodion  as of release 1.9.2, the concept of overflow has been added to text component. You can create columns of text and decide how to handle the results of too much text for the given space. See wiki for examples.

**Comment by hugodion** [comment]
Great ! Thank you!
