### ISSUE TITLE
Making a single word of a text line bold.

### ISSUE THREAD

**Issue by kaumudpa** [chunyenHuang/hummusRecipe#167]
Lets consider an example where we have a line. : 'This is Test'

How do i achieve doing 'This is **Test**' while adding this line to an existing pdf?

**Comment by shaehn** [comment]
View the Text Flow examples for an idea. https://github.com/chunyenHuang/hummusRecipe/wiki/Text-Flow

**Comment by kaumudpa** [comment]
Ok! sounds promising, will look into it. Thank you.

**Comment by kaumudpa** [comment]
The option `flow` is not available.

This what i am trying to implement.
```
.text('This agreement Created on', 'center', height - 14, {
            flow:true,
            color: 'red',
            fontSize: 6,
            // maxLines: 2,
            // minLines: 2,
            // // bold: true,
            font: 'Anonymous',
            // align: 'center center',
            highlight: true,
            textBox:{padding:p ,width: w, textAlign:'center'}
        })
```

After adding `flow:true,` The text is not added.

The available options in `text` is :
```
 interface TextOptions {
        color?: string | number[];
        opacity?: number;
        rotation?: number;
        rotationOrigin?: number[];
        font?: string;
        size?: number;
        align?: string;
        highlight?: boolean;
        underline?: boolean;
        strikeOut?: boolean;
        textBox?: TextBox;
    }
```
(The option of flow is missing.)
The version of hummus-recipe is 1.9.2

**Comment by kaumudpa** [comment]
This is working.
Things to remember - 
While using to flow remember to close the flow with `flow:false` .
