### ISSUE TITLE
Not able to create table in existing PDF

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [chunyenHuang/hummusRecipe#168]
Hi, I'm trying to create table in existing PDF, referring https://hummus-recipe.s3.amazonaws.com/docs/Recipe.html#.table , but unfortunately it throws error `Cannot read property '2' of undefined`.
    
     const invoicePDF = new Recipe('input.pdf', 'output.pdf');
     let content = [{
                name: "Steven Haehn",
                address: "257 Banana Ave.",
                city: "Colorado Springs",
                state: "Colorado",
                job: "computer programmer"
            }];
    invoicePDF.editPage(1).table(10,100,content).endPage().endPDF();`

**Comment by shaehn** [comment]
I found the problem and have put in a PR. Look at wiki for general documentation on tables.

**Comment by Suroor-Ahmmad** [comment]
Is this issue resolved?

**Comment by shaehn** [comment]
Yes it has. See above merge pull.
