### ISSUE TITLE
Crashes inside Alpine docker

### ISSUE THREAD

**Issue by AyushG3112** [chunyenHuang/hummusRecipe#170]
Node.js Version: 10.15.0
hummus-recipe: V1.9.2

Hi,

I am trying to add image to an existing PDF using `.image` . It works working on my local machine (Ubuntu 16.04), however it crashes inside the Alpine container on calling `endPDF`(thus creating a corrupted PDF).

Tried downgrading to v1.7.4, didn't help.

Any help is appreciated.

**Comment by chunyenHuang** [comment]
Can you share your `Dockerfile` for alpine?

**Comment by AyushG3112** [comment]
My `Dockerfile` looks like:

``` Docker
FROM node:10.13.0-alpine

RUN mkdir -p /var/app/
WORKDIR /var/app/
ENV NODE_ENV=development

RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/dow
nload/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C /
RUN mkdir -p /var/app/templates/tmp
RUN apk add pdftk
RUN npm config set strict-ssl false
RUN npm install -g nodemon
RUN npm install -g nyc
RUN npm install -g mocha

EXPOSE 3000

CMD ["./dev-start.sh"]
```

`dev-start.sh` runs `npm install` and starts my service using `nodemon`

Here's my `hummus-recipe` integration:

``` js
    const pdfDoc = new HummusRecipe(input, output);
    pdfDoc
      .editPage(2)
      .image('/path/to/image1.png'), 350, 660, {
        width: 200,
        keepAspectRatio: true,
      })
      .image('/path/to/image2.png'), 125, 740, {
        width: 50,
        keepAspectRatio: true,
      })
      .endPage()
      .endPDF(console.log);

```

**Comment by AyushG3112** [comment]
Might be worth noting that I also ran

``` console
apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
```

Inside the container, then restared by app, but to no avail.

**Comment by chunyenHuang** [comment]
Thanks for sharing. Would you like to give this a try?

https://github.com/galkahana/HummusJS/issues/320#issuecomment-417942705
> We were able to solve this problem by including make, gcc, g++, and python in our Alpine container and running npm rebuild hummus --build-from-source.

**Comment by AyushG3112** [comment]
@chunyenHuang Thanks that works!

For posterity, we had to add the following things to our `Dockerfile`:

``` Docker
RUN apk add  g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install -g node-gyp 
RUN npm install
RUN npm rebuild hummus --build-from-source
```

**Comment by AndreHermanto** [comment]
I come across this issue, but the solution given doesn't work for me. This is my Dockerfile 

```
FROM node:10.13.0-alpine

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN apk add  g++ gcc libgcc libstdc++ linux-headers make python
RUN npm install -g node-gyp 
RUN npm install

RUN npm rebuild hummus --build-from-source

COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
```

I have used "hummus-recipe": "^1.9.2" and node:10.13.0-alpine, but still got this following error in the container
```
internal/modules/cjs/loader.js:717
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Error loading shared library /usr/src/app/node_modules/hummus/binding/hummus.node: Exec format error
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/node_modules/hummus/hummus.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

**Comment by AyushG3112** [comment]
@AndreHermanto can you `sh` inside the container and verify that the `node_modules/hummus` directory exists in your `WORKDIR`?

**Comment by AndreHermanto** [comment]
@AyushG3112 I can't ssh into container as the container exited immediately. Is my Dockerfile correct?

**Comment by AyushG3112** [comment]
@AndreHermanto seems fine but I've seen issues when `npm install` is ran from a Dockerfile. Not exactly sure what causes it though. Also, to `sh` into the container, replace

```
CMD [ "npm", "start" ]
```

with

```
CMD ["sh"]
```

I think that should work

**Comment by AndreHermanto** [comment]
@AyushG3112 Its the same, the container still exited immediately.

**Comment by Suroor-Ahmmad** [comment]
Any resolution for this issue? I tried all above mentioned methods and still no help

**Comment by hdiaz-nectia** [comment]
I've a similar problem, and the above solution doesn't work for me.

Dockerfile
node:12.19-alpine

```
console.log('New');
const pdfDoc = new HummusRecipe(filenameSrc, filenameEnc);
console.log('Encrypt');

pdfDoc
    .encrypt({
        userPassword: key,
        ownerPassword: key,
        userProtectionFlag: 4
    })
    .endPDF();

console.log('End');
```

The last step executed is log _Encrypt_ an then exit from docker container.

**Comment by hdiaz-nectia** [comment]
> Hi @chunyenHuang @AyushG3112
> I've a similar problem, and the above solution doesn't work for me.
> 
> Dockerfile
> node:12.19-alpine
> 
> ```
> console.log('New');
> const pdfDoc = new HummusRecipe(filenameSrc, filenameEnc);
> console.log('Encrypt');
> 
> pdfDoc
>     .encrypt({
>         userPassword: key,
>         ownerPassword: key,
>         userProtectionFlag: 4
>     })
>     .endPDF();
> 
> console.log('End');
> ```
> 
> The last step executed is log _Encrypt_ an then simply it exit from docker run. Last log never is printed (and any other error) and when I go inside container with _docker exec_ i saw that the destination file has 0 size.

My mistake, the correct is:

`RUN npm rebuild muhammara --build-from-source`
