### ISSUE TITLE
In-place edit an existing pdf

### ISSUE THREAD

**Issue by saadb** [chunyenHuang/hummusRecipe#18]
I want to in-place edit a pdf page, but want to save changes to the existing pdf not create a new pdf, what do you suggest I go about doing this? thank you in advance

**Comment by chunyenHuang** [comment]
Good advise, it is possible. Let me make a quick change for it.

**Comment by chunyenHuang** [comment]
ok You should be able to overwrite the source pdf now after `1.4.5`. The other workaround is to have output and source the same path.
https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/modify-in-place.js

**Comment by chunyenHuang** [comment]
@saadb Do you still need help for this?
