### ISSUE TITLE
Change dependency to muhammarajs

### ISSUE THREAD

**Issue by sjaakieb** [chunyenHuang/hummusRecipe#186]
Since Hummus is not maintained anymore (as discussed here : https://github.com/galkahana/HummusJS/issues/447), there are no binaries being build for newer node and electron versions. Julian Hille (https://github.com/julianhille) has made a fork and has indicated he is willing to maintain it.

**Comment by Felipedelima123** [comment]
I was about to comment this. @chunyenHuang also mentioned that was thinking about forking, maybe they can both work together.

**Comment by chunyenHuang** [comment]
Let me think about this one. We may end up to use both...
