### ISSUE TITLE
Insert first page not working

### ISSUE THREAD

**Issue by davidduffett** [chunyenHuang/hummusRecipe#19]
When I try to insert the first page into a PDF it fails with `unable to append page, make sure it's fine`.

```
recipe.insertPage(0, '/tmp/other.pdf', 1).endPDF();
```

I'm fairly sure the offending code is [in here](https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/insertPage.js#L44) - something about when you're constructing the new PDF, it might be trying to get a page -1 from the original?

At the moment I'm fairly sure `insertPage` only works for page 2 onwards.

**Comment by chunyenHuang** [comment]
Oh! You are right about the first page thing. I also found another bug for the missing pages during inserting. I have fixed it and you should be able to run the same code and get the result.  
Please update to `1.4.7`.

**Comment by davidduffett** [comment]
@chunyenHuang Thanks a lot for the amazing quick turnaround on this - works great now.
