### ISSUE TITLE
PDF encryption take too long?

### ISSUE THREAD

**Issue by Solid-Metal** [chunyenHuang/hummusRecipe#197]
just use this, and notice that when i encrypt my pdf, it take too long and cause server socket timeout, is there any reason for this? and how to fix it ?

the pdf fairly simple report pdf, with 500kb size

heres the snippet : 
```js
await fsPromises.writeFile(`./stash/input.pdf`, result, { encoding: 'base64' })
          .then(() => {
            logger.debug('pdf saved');

            const pdfDoc = new HummusRecipe(`./stash/input.pdf`, `./stash/output.pdf`);
            logger.debug("start encrypt");
            pdfDoc
              .encrypt({
                userPassword: body.password,
                userProtectionFlag: 3
              })
              .endPDF();
            logger.debug("encrypt done");
          })
          .catch(er => {
            logger.error(er);;
          });
```

**Comment by chunyenHuang** [comment]
Unfortunately encryption has to write to a new file instead of caching in memory, can you check if it's permission issue?

**Comment by Solid-Metal** [comment]
sorry i might be not put enough detail, while its indeed socket time out, but the encryption still work , it just took a long time , i test for 3kb pdf work just fine, 500kb on the other hand need about 2 minutes, is there any workaround for this ?

**Comment by Solid-Metal** [comment]
might need to add new comment

while this library is great, it work just fine on client side, but on server it too source consuming, i change to use qpdf with exec for my encryption and merging need, still an awesome library nontheless, thanks !
