### ISSUE TITLE
How to modify a file?

### ISSUE THREAD

**Issue by pedro-surf** [chunyenHuang/hummusRecipe#199]
Hi, thanks for this good-looking lib!
I can't figure out how to use it.

The examples shown to modify a document pass string as parameters.

How can I load a PDF passing binary data?!

**Comment by chunyenHuang** [comment]
https://github.com/chunyenHuang/hummusRecipe/blob/b4051b2076479a318c779ae30ec59a2c836832e4/tests/createWithBuffer.js#L36
