### ISSUE TITLE
Splitting PDF pages produces variable byte contents

### ISSUE THREAD

**Issue by austincondict-AngelOak** [chunyenHuang/hummusRecipe#212]
I'm currently using the split PDF functionality of this package and have come across an issue.
After splitting the exact same source PDF file into its component pages, I am leveraging the `crypto` module to generate a SHA-1 hash for each page's byte content `Buffer` and storing the hash in a DB for performing duplicate page checks. Each time I split this source PDF, each page will produce a different hash value than it did before. The content hash of the source PDF remains constant.

So despite the pages being visually identical when opened in Adobe Acrobat, the byte contents are being changed slightly by the split operation. This results in non-deterministic hashing which makes it impossible to use for dupe checking / file diffing. Any idea as to what could be changing within the page contents during the split operation? Or any workarounds for this?

**Comment by shaehn** [comment]
I don't think what you are doing is going to be possible, at least in the manner you have chosen to do it. I remember years ago someone had told me the only way to check for PDF page differences was to convert the PDF page into a graphic page, say JPG format, and do the difference checking from the resulting file. Apparently, the construction of PDF content varies from each usage of code. Perhaps there are date stamps embedded. Whatever the case, graphic conversion is probably the only way to get a consistent result.

**Comment by austincondict-AngelOak** [comment]
Thanks for the insight @shaehn, I considered the same workaround myself (converting the PDF pages to PNGs prior to hashing) and that's actually the approach I've ended up taking.
