### ISSUE TITLE
Draw image using base64 representation of image

### ISSUE THREAD

**Issue by modood** [chunyenHuang/hummusRecipe#22]
Is there option to draw image using base64 representation of image?

"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAAgAElEQVR4nNS6Z1xVaZbvv/c+CVOZc6mYEMlJMZRizgljGRARs6AgOSMGQATBSM5ZyTkoOQkSzJWrp3t6etLt6Z7pmf/c++L7f3EOiBZW2dM9dz73xfdzztl7n3Oe/Txrrd9a69mCTC4gkwvIZAKSTECUBARRQBA+jii+46f ...."

**Comment by chunyenHuang** [comment]
HummusJS does not provide that out of box. [Image](https://github.com/galkahana/HummusJS/wiki/Show-images#simple-image-drawing)
So you may still have to save it as a file in order to use it with HummusJS.

**Comment by modood** [comment]
That's what I did and it works :smile:
