### ISSUE TITLE
merge code into muhammara

### ISSUE THREAD

**Issue by julianhille** [chunyenHuang/hummusRecipe#240]
hey i want to merge this code directly into muhammara. 
Are there any objections to it?

**Comment by maximveksler** [comment]
This seems depreacted, and the depenedcy on `"muhammara": "^2.1.0"` is quite old. Mereging it would be great for the community IMHO.

**Comment by julianhille** [comment]
https://github.com/julianhille/MuhammaraJS/issues/232 there is already a ticket and i hope i can start that soon.

**Comment by maximveksler** [comment]
> [julianhille/MuhammaraJS#232](https://github.com/julianhille/MuhammaraJS/issues/232) there is already a ticket and i hope i can start that soon.

Thank you :+1: 

This is truly good, as currently when adding `hummus-recipe` the version of muhammara that is picked up is 1.10, which is quite old.

```
pnpm why muhammara             
Legend: production dependency, optional only, dev only

demo@1.0.0 /home/m/code/pr/CoreLess/apps/demo

dependencies:
hummus-recipe 2.0.1
└── muhammara 1.10.0
```

**Comment by julianhille** [comment]
has been merged
