### ISSUE TITLE
Overlay issue

### ISSUE THREAD

**Issue by tmwd** [chunyenHuang/hummusRecipe#26]
### Usage:
```javascript
const HummusRecipe = require('hummus-recipe')
const pdfDoc = new HummusRecipe('input.pdf', 'output.pdf')
const pdfOverlay = 'overlay.pdf'
pdfDoc
    .editPage(1)
    .overlay(pdfOverlay, 0, 0)
    .endPage()
    .endPDF()
```
### hummus-error.log:
```
[ 06/02/2018 16:57:15 ] UnicodeString::FromUTF16BE, fault string - high surrogat encountered without a low surrogate
[ 06/02/2018 16:57:15 ] UnicodeString::FromUTF16BE, fault string - high surrogat encountered without a low surrogate
```
### Result:
PDF file was not changed, just copied from input to output.
### Question:
Can you please help me out with this?

**Comment by chunyenHuang** [comment]
I think there is a bug in the overlay coordinate. Can you try without the `x` and `y`?
```javascript
pdfDoc
    .editPage(1)
    .overlay(pdfOverlay)
    .endPage()
    .endPDF()
```

Besides this, the source code is from 
https://github.com/galkahana/HummusJS/blob/fdfe49b60b15c13c692885bdf5d9aae18d303f92/src/deps/PDFWriter/UnicodeString.cpp#L208

**Comment by tmwd** [comment]
@chunyenHuang Thank you! It works without coordinates! However, still have same logs.

**Comment by tmwd** [comment]
@chunyenHuang It works without coordinates, but same records appears in log.

**Comment by chunyenHuang** [comment]
I think you may have to post this issue in [HummusJS Issue](https://github.com/galkahana/HummusJS/issues) since this can not be handled in this repo.

**Comment by tmwd** [comment]
@chunyenHuang I've implemented overlay with HummusJS, so I think this is hummusRecipe issue

**Comment by chunyenHuang** [comment]
Is it possible to send me the pdf file? I will check again. Thanks
little78926@gmail.com

**Comment by chunyenHuang** [comment]
@tmwd Hello do you still have this issue?
