### ISSUE TITLE
overlay() not showing on output

### ISSUE THREAD

**Issue by hannesw** [chunyenHuang/hummusRecipe#28]
I'm using the following code to overlay one pdf to a blank page (final goal is to make some imposition software). But the output is always empty. Files are attached.

```JS
const pdfDoc = new HummusRecipe('input.pdf', 'output.pdf');

    pdfDoc
        .editPage(1)
        .overlay('overlayPDF.pdf')
        .endPage()
        .endPDF();
```

[output.pdf](https://github.com/chunyenHuang/hummusRecipe/files/1724360/output.pdf)
[overlayPDF.pdf](https://github.com/chunyenHuang/hummusRecipe/files/1724361/overlayPDF.pdf)
[input.pdf](https://github.com/chunyenHuang/hummusRecipe/files/1724362/input.pdf)

`
Windows 10 x64
Node 9.5.0
`

**Comment by chunyenHuang** [comment]
Thanks for reporting this. I believe the issue is the coordinate bug for overlay #26.
I will update and fix it soon.

**Comment by chunyenHuang** [comment]
Please update to `v1.6.0`.
You may also find new examples here https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/overlay.js

**Comment by hannesw** [comment]
@chunyenHuang Works like a charm! Thank you very much for your work!
