### ISSUE TITLE
Request: Text Rotate

### ISSUE THREAD

**Issue by nothingasis** [chunyenHuang/hummusRecipe#34]
Came across Issue #167 on HummusJS (https://github.com/galkahana/HummusJS/issues/167) and chunyenHuang's implementation for rotating text.

Could we also add this feature to the options in HummusRecipe?
Example:
```
let pdfDoc = new HummusRecipe(...)
          pdfDoc.text(watermark, xOffset, yOffset, {
            color: 'ff0000',
            opacity: 0.3,
            fontSize: 48,
            bold: true,
            font: 'Helvetica',
            align: 'center top',
            rotateText: 90 // 0 - 360 degrees
          })

```

**Comment by chunyenHuang** [comment]
I believe it will be a great feature. But talking about rotation, I do have some questions:
1. Where is the center point for rotation?
2. Will this rotation should be applied to the following actions or just this one?

We can discuss here and come out with the implement strategy before I add it to the repo.

**Comment by nothingasis** [comment]
Hey chunyen, thanks for getting back to me on this.

1. Where is the center point for rotation?
Maybe, default rotation point is center of text. Taking from the Microsoft Word example here.

So if...
If typeof === string, predefined options are "horizontal", "vertical" where rotation is center of text.
Else If typeof === Object, Options are: 
anchor: [ anchorX, anchorY ],
rotation: 0 - 360



2. Will this rotation should be applied to the following actions or just this one?
I believe it should apply only this one action; keep the rotation local to the action.

**Comment by chunyenHuang** [comment]
It seems to me that it can be really to find the center of the text. What about using the `x, y` from the text coordinate?

**Comment by nothingasis** [comment]
That would work too. So instead of being able to pass in just a string for horizontal or vertical, you would pass in options for the x, y coordinates for the point of rotation and the degree of rotation?

**Comment by chunyenHuang** [comment]
So how about this?
```javascript
          pdfDoc.text(watermark, x, y, {
            align: 'center top',
            rotate: 90 // 0~360 degrees,
            rotateCenter: [ rX, rY ]
          })
```

It seems to me that using `string: horizontal/vertical` is vague in the direction. I prefer using number (0~360)

**Comment by nothingasis** [comment]
This will prove to be very helpful, I'll take it. Thank you!

**Comment by Fiiii** [comment]
Is there any chance to do quick release of this :D ? I'm working with lambda implementation of watermark and rotate option would be great 🍻 !

**Comment by chunyenHuang** [comment]
Hello @nothingasis @Fiiii 
You can now test the text rotation in `1.7.0`
https://chunyenhuang.github.io/hummusRecipe/Recipe.html#.text

**Comment by Fiiii** [comment]
Great ! 👍 🥂 🎉 I'm starting to create lambda for test it , Thanks !

**Comment by Fiiii** [comment]
Weird but I occur this error:
`(node:27287) UnhandledPromiseRejectionWarning: SyntaxError: Identifier 'targetAnnotations' has already been declared`

I copy/paste code for modify pdf

**Comment by chunyenHuang** [comment]
yah, I can see that error too 
https://travis-ci.org/chunyenHuang/hummusRecipe/jobs/385370774#L461
I will patch it soon.

**Comment by chunyenHuang** [comment]
`1.7.1` should have removed the bug.

**Comment by Fiiii** [comment]
Thanks ! Checking it :)

**Comment by Fiiii** [comment]
@chunyenHuang  Unfortunately, I have another error (`module initialization error: Error`) connected with hummus js .... I think its about missing `bindings/hummus.node` :/

**Comment by Fiiii** [comment]
The most weird part of it is that locally it works :D

**Comment by chunyenHuang** [comment]
@Fiiii You will need to compile hummusJS against the lambda environment (not your local environment) for lambda function. https://github.com/chunyenHuang/hummusRecipeForLambda#hummus-in-lambda

**Comment by nathanbrizzee** [comment]
ChunyenHuang, this is an awesome library you have.  I updated my code to use the new rotation feature.  Works great!.  How much work would it take to be able to rotate on 45 degree increments instead of just 90?  I'm using the library to watermark PDF's we have, and generally watermarks go from the bottom left corner to the top right corner centered in the center of the page.  I can only rotate 90, or 270.  It would be great if I could rotate 45 (or -45) to achieve this direction with watermarks.
Thanks very much.

**Comment by nothingasis** [comment]
Reopening.. Nathan made a good point with rotations. 90° angles were already working but 45° was the purpose of the proposal.

**Comment by chunyenHuang** [comment]
ok I will add to the next release

**Comment by danhalliday** [comment]
I just added support for arbitrary rotation angles in PR #47. Let me know what you think, or if there are any mistakes!

**Comment by chunyenHuang** [comment]
@danhalliday Thanks for you help, your PR has been merged.

**Comment by nathanbrizzee** [comment]
Awesome! Thanks.  See my post in PR #47 for an example on how I used it.
