### ISSUE TITLE
Is it possible to edit scanned PDF files?

### ISSUE THREAD

**Issue by christiansaiki** [chunyenHuang/hummusRecipe#38]
I'm pretty pleased to use this awesome library! Thank you so much @chunyenHuang 
Nevertheless I'm having trouble to edit a scanned PDF file.
I keep getting `Segmentation fault: 11`
I do not have any other log from the project

My current code is

```javascript
const projectExample = {
	socinal_contract_id: '222222222'
};


/**
 * addContractIdInPdf - this function is responsible for adding the CCB Number
 * into an already signed and scanned contract
 * It will return the path of the new pdf file
 * @param  {Object} project  - a project object from MongoDB
 * @param  {String} inputPath - the path of the pdf file that will be processed
 * @return {String} outputPath - the path to the new pdf file
 */
function addContractIdInPdf (project, inputPath) {
	return new Promise((resolve) => {
		const pathWithoutExtension = inputPath.replace(/\.[^/.]+$/, '');
		const newFilePath = `${pathWithoutExtension}_with_contract_id.pdf`;
		const pdfDoc = new HummusRecipe(inputPath, newFilePath);
		pdfDoc
		// edit 1st page
			.editPage(1)
		// add text to pdf
			.text(project.socinal_contract_id, 420, 64)
		// we MUST use endPage!!
			.endPage()
			.editPage(7)
			.text(project.socinal_contract_id, 200 , 343)
			.text(project.socinal_contract_id, 285, 392)
			.endPage()
		// end and save
			.endPDF(() => resolve(newFilePath));
	});
}

addContractIdInPdf(projectExample, '/tmp/02121402.pdf')
.then((path) => console.log(path))
```
It works perfectly for digital pdf files, and it doesn't work for scanned pdf files.
Thank you so much for your help

**Comment by chunyenHuang** [comment]
`Segmentation fault: 11` usually happens when you have wrong file path for pdf input, output or font.
You may console log the file path or use something like `path.join(__dirname, FILEPATH)` to prevent relative file path issue.

**Comment by christiansaiki** [comment]
Thank you, but the thing is that It works perfectly for digital pdf files, and it doesn't work with scanned pdf files.
I am putting both files in the same directory, but for some reason HummusJS doesnt work with scanned pdf files, do you know why?
Best Regards

**Comment by chunyenHuang** [comment]
I think it can relate to the bug #41 . Can you send me some failed pdfs? little78926@gmail.com

**Comment by christiansaiki** [comment]
Thank you so much, I've just sent you the file

**Comment by christiansaiki** [comment]
I can confirm that it is related to #41 
I've commented the call to this._writeInfo() function and then it started to work.
But I dont know why.
Best Regards

**Comment by chunyenHuang** [comment]
sry I still need time for this. It seems to me that `documentParser` from HummusJS is broken.

**Comment by christiansaiki** [comment]
Alright I appreciate all of your effort! 
Best regards

**Comment by chunyenHuang** [comment]
@christiansaiki Please update to 1.7.3
It temporarily disables the blocker codes until HummusJS updates.

**Comment by christiansaiki** [comment]
Thank you so much!
