### ISSUE TITLE
Cannot save PDF (Exited from signal: SIGSEGV)

### ISSUE THREAD

**Issue by MikeAwie** [chunyenHuang/hummusRecipe#41]
I am using hummus-recipe in a Meteor app to mark some PDF's but some PDF's are failing. The pdfs are also made using hummus-recipe and the ones that are failing are specifically the ones that are made only by adding images to a pdf. When i try to mark those i get Exited from signal: SIGSEGV.
I can provide you with an example PDF in private since it contains some personal information.
This is the code i use to mark the PDF's:
```try {
            const pdfDoc = new HummusRecipe(pdfPath, pdfPath);
            console.log('marking pdf')
            pdfDoc
                .editPage(1)
                .text(`Anlage K${k}`, 375, 35, {
                    color: '#000000',
                    fontSize: 24,
                    bold: true,
                    align: 'center center',
                    textBox: {
                        width: 162,
                        minHeight: 32,
                        lineHeight: 18,
                        textAlign: 'center center',
                        padding: [5, 15],
                        style: {
                            lineWidth: 5,
                            stroke: '#020202'
                        }
                    }
                })
                .endPage()
                .endPDF(() => appendPage(pdfPath));
        } catch (err) {
            console.log(`didnt append K${k}}`)
        }

**Comment by chunyenHuang** [comment]
Hi, I think you have to use different `pdfPath` for the output, hummusJS can not write to the original file.

**Comment by MikeAwie** [comment]
That's not the problem, I tried with a different path too still the same issue only for the PDF's created with images. And I'm pretty sure writing to the original file works. Could i send you a sample of the PDF I'm talking about?

**Comment by chunyenHuang** [comment]
That will be helpful little78926@gmail.com

**Comment by MikeAwie** [comment]
Any update? Did you try the file I sent you?

**Comment by MikeAwie** [comment]
I found that the issue occurred at the endPDF function in Recipe.js . Specifically at this._writeInfo();
So i added an exception to not run this._writeInfo(); and it works now.
Is that line important?

**Comment by chunyenHuang** [comment]
Hello @MikeAwie ,
You are right about the bug. 
https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/info.js#L28
It can not parse the info from the source file. I will make a fix soon.

**Comment by chunyenHuang** [comment]
Hi all, sorry that I still can not get it work in HummusJS. So I have to disable the codes until Gal can help to fix it. You guys can use `1.7.3` to avoid this issue.
