### ISSUE TITLE
How to add Chinese character to pdf？

### ISSUE THREAD

**Issue by JarvisQJ** [chunyenHuang/hummusRecipe#45]
I try to add Chinese character to pdf,but i got nothing,no error message,no Chinese character.

**Comment by JarvisQJ** [comment]
Actually,i got a blank space one Chinese charater.

**Comment by JarvisQJ** [comment]
@chunyenHuang

**Comment by chunyenHuang** [comment]
Hi 你好
You may register and use the font [`PMingLiU`](http://www.fontpalace.com/font-details/PMingLiU)
Here is the example:
https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/font.js

**Comment by JarvisQJ** [comment]
@chunyenHuang thank you,but,where is the 'materials/fonts'

**Comment by JarvisQJ** [comment]
thank you,i got font file [here](http://www.fontpalace.com/font-download/PMingLiU/),after a puzzling verify.
