### ISSUE TITLE
app crashes on pdfDoc.endPDF()

### ISSUE THREAD

**Issue by curtisnn** [chunyenHuang/hummusRecipe#48]
Could use a little help here. Looks like a perfect library for what I need, just haven't been able to get it working. I'm running this code: 

```const HummusRecipe = require('hummus-recipe');
    const pdfDoc = new HummusRecipe('./input.pdf', './output.pdf');
    pdfDoc.editPage(1)
        .text('adding test text', 10, 10)
        .endPage()
        .endPDF();
```

When I trace the issue, it is failing inside this block of code, specifically in the call to queryDictionaryObject: 

```exports._writeInfo = function _writeInfo() {
    const options = this.toWriteInfo_ || {};
    let oldInfo;
    if (!this.isNewPDF) {
        // reuse copyCtx?
        const copyCtx = this.writer.createPDFCopyingContext(this.src);
        oldInfo = copyCtx.getSourceDocumentParser().queryDictionaryObject(
            copyCtx.getSourceDocumentParser().getTrailer(), "Info"
        ).toJSObject();
```

If I comment out this block of code, it works, but it doesn't feel like the right way to handle this ... any suggestions?

**Comment by chunyenHuang** [comment]
Hi this issue is related to #41 
I will make this function disabled until it gets fixed in HummusJS.
