### ISSUE TITLE
A way to not wrap text within textbox?

### ISSUE THREAD

**Issue by curtisnn** [chunyenHuang/hummusRecipe#52]
Just wondering if there is a way to prevent text wrapping, for example, I sent in this text
`"company\nmore test\nmore test that is something really long and annoying\nsomething else to see\ncountry",` with a width of 1.5" (1.5 *  72).

I expected:
Company
more test
more test that is something re ...  <-- This line clipped
something else to see
country

Instead I got this results
<img width="138" alt="final-small-folded-landscape_pdf__page_3_of_24_" src="https://user-images.githubusercontent.com/14912039/44557744-53f06400-a6fd-11e8-9673-e465176d7a2e.png">

My overall goal is that I need to limit the output to 5 printed lines. and a fixed width.

As a side question, any idea why the 'g's are getting cut off in the above picture? I've tried setting lineHeight, but that didn't seem to have an effect.

Any suggestions?
Thanks!

**Comment by chunyenHuang** [comment]
Well, this is a really complicated question haha. The text alignment is a pain for this repo. I will see what I can do to get this fix.

**Comment by Chrisjow** [comment]
Hi, is this issue fixed? I am very interested in a feature like this!
Thanks

**Comment by shaehn** [comment]
The final solution has been checked in so you can now try it out. The wrap option can take on a string value ('auto', 'clip', 'trim', 'ellipsis'), or a boolean value (true, which is equivalent to 'auto' and false, which is equivalent to 'ellipsis'). 'Clip' will slice the word that won't fit right at the text boundary. 'Trim' removes the words that won't fit on the line. 'Ellipse' puts '...' at the end of the line that has more text than can fit in the box.
