### ISSUE TITLE
getting info from existing pdf

### ISSUE THREAD

**Issue by aminify** [chunyenHuang/hummusRecipe#53]
how can we get number of pages and also size of each page?
I couldn't find it in repo
for example, say I want to add a text on top of all pages of current pdf file, how can I approach this problem?

**Comment by chunyenHuang** [comment]
ola, there are two ways to get the info
1. metadata https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/Recipe.js#L104
2. structure https://github.com/chunyenHuang/hummusRecipe/blob/master/tests/info.js#L37

Technically, you can get the info from Recipe

```javascript
const recipe = new HummusRecipe(src, output);
console.log(recipe.metadata);
```

**Comment by AminMMZ** [comment]
thank you, metadata was the ultimate way for all the info about pdf. it would be good if it was mentioned in docs so everyone can know about it.

**Comment by chunyenHuang** [comment]
Will add it in the next release.

**Comment by chunyenHuang** [comment]
https://github.com/chunyenHuang/hummusRecipe#page-info
