### ISSUE TITLE
resize page

### ISSUE THREAD

**Issue by vegarringdal** [chunyenHuang/hummusRecipe#58]
Looks like you know everything about hummusjs

Ive been trying to resize but markup/comments are not copied, do you know if there is something Ive missed

![image](https://user-images.githubusercontent.com/2901416/45588200-333cb800-b911-11e8-9206-8e277c041d34.png)

```
const hummus = require('hummus');
const path = require('path');
const file_path = path.resolve(__dirname, './original.pdf')
const resizeWriter = hummus.createWriter(path.resolve(__dirname, './test.pdf'))
const resizeReader = hummus.createReader(file_path)
const resize_page_count = resizeReader.getPagesCount()


// A4 size
const maxWidth = 210;
const maxHeight = 297;


for (let i = 0; i < resize_page_count; i++) {

  // get media box so I can get width and height
  const onepage = resizeReader.parsePage(i);
  const getMediaBox = onepage.getMediaBox();

  //get new width and height based landscape/portrait
  let width = getMediaBox[2] > getMediaBox[3] ? maxHeight : maxWidth;
  let height = getMediaBox[2] > getMediaBox[3] ? maxWidth : maxHeight;


  const page = resizeWriter.createPage(0, 0, width, height)
  const pageContent = resizeWriter.startPageContentContext(page)

  pageContent
    .q()
    .drawImage(0, 0, file_path, {
      index: i,
      transformation: {
        width: width,
        height: height,
        proportional: true
      }
    })
    .Q()

  resizeWriter.writePage(page)
}

resizeWriter.end() 
```

**Comment by chunyenHuang** [comment]
hi @vegarringdal 
I am sure what do you want to achieve? Can you describe it with more details? 
- What do you wan to do?
- What is your expectation and what's the actual result?

**Comment by vegarringdal** [comment]
@chunyenHuang 

Hi
I work with pdf in all sizes with a lot of markup on them.
Problem is that this isnt very userfrendly when it comes to printing.
So what I want to do it loop the pages.
If a page is smaller then A4 then I set it to A4, if its larger I need to set it to A3.
I managed to do this, only markups/stamps are lost.

**Comment by chunyenHuang** [comment]
The issue is pretty common in HummusJS. Since you modify the page context, so you will need to copy the original context to the new one otherwise everything will be gone. 

https://github.com/galkahana/HummusJS/blob/b699d6a01ba027428120cbe5b1c16813bed0521d/tests/ModifyingExistingFileContent.js

And you may re-post this issue in HummusJS since your question is more related to it.

**Comment by vegarringdal** [comment]
ok , thx.
Was hoping you knew a trick I could do with the drawimgae that m,ade it include everything in the pdf source

**Comment by chunyenHuang** [comment]
I mentioned in the last reply
> so you will need to copy the original context to the new one otherwise everything will be gone

**Comment by vegarringdal** [comment]
@chunyenHuang 
Thankx

Created this:
https://github.com/galkahana/HummusJS/issues/327

I clearly have a lot to learn about hummusJS 😄 
closing this issue
