### ISSUE TITLE
Crash when trying to editPage during creation of 'new' PDF document

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#60]
I wanted to create a new PDF document by initially appending some pages from another document and then edit the pages on that document. For example,

![image](https://user-images.githubusercontent.com/13596544/46086371-ef01b100-c175-11e8-9e53-b09e896abb5d.png)

However, when I did this, I got the following error.

![image](https://user-images.githubusercontent.com/13596544/46086432-12c4f700-c176-11e8-9dde-d039bc302ff9.png)

So does editing only work for pre-existing documents, and not while a new one is being created?

**Comment by shaehn** [comment]
Is this a hummus bug, or one in hummus-recipe?

**Comment by chunyenHuang** [comment]
https://github.com/galkahana/HummusJS/issues/139

I dont think the `editPage` can be used in a new pdf.

**Comment by shaehn** [comment]
Yes, after studying the code, one cannot edit a 'new' file. It has to be created first, closed, then it can be edited afterwards.
