### ISSUE TITLE
Characters get  trimmed when applying rotation to existing PDF

### ISSUE THREAD

**Issue by kmohideen-xybion** [chunyenHuang/hummusRecipe#67]
I am trying to do watermarking using existing PDF, when I use below piece of code, some of the characters are not visible fully using  'Hummus-Recipe'  

//Stamping - Start
    const HummusRecipe = require('hummus-recipe');
    let src = 'E:/SCC/GitHub Repository/xybion-api/server/lib/doctopdf/pdf/input1.pdf';
    const recipe = new HummusRecipe(src, 'E:/SCC/GitHub Repository/xybion-api/server/lib/doctopdf/pdf/Output.pdf');

    recipe
        .editPage(1)
        .text('Hummus-Recipe pqy', 'center', 'center', {
            color: '#0000FF',
            fontSize: 30,
            bold: true,
            font: 'Courier New',  // Arial,Helvetica,sans-serif",
            align: 'center center',
            opacity: 1,
            rotation: 310,

        })
        .endPage()
        .endPDF();
    //Stamping - End

![capture](https://user-images.githubusercontent.com/15813569/48756443-3a8c9300-ecbf-11e8-86dc-74dfeb5f1da7.JPG)

I have commented rotation and its working fine.Please guide me, how to use with rotation.
![capture](https://user-images.githubusercontent.com/15813569/48756519-7e7f9800-ecbf-11e8-893b-23f069ade1af.JPG)

Thanks in Advance.

Regards,
Kashif.S

**Comment by chunyenHuang** [comment]
Fix in `hummus-recipe@1.8.2`
