### ISSUE TITLE
The font gets clipped when using opacity value less than '1'

### ISSUE THREAD

**Issue by dasdboot** [chunyenHuang/hummusRecipe#71]
Hi, thank you for the hummus receipt and your invaluable support of it. I found a small issue when adding text to an existing pdf. It seems that if the opacity value is less than one used the text gets clipped, please see the examples below:

code:
<snip>
pdfDoc
    // edit 1st page
    .editPage(1)
    .text('Tyler Durden', 'center', 175, 
       {color: '000000',
       fontSize: 30,
       align: 'center center',
       bold: false,
       font: 'Arial',
       opacity: 0.8} )
    .endPage()
    .endPDF(); 

results in:
![image](https://user-images.githubusercontent.com/6440523/50589078-1346eb00-0e53-11e9-91f8-a7bb7b9f625c.png)

if the opacity is set to: 1 the result is as follows:
![image](https://user-images.githubusercontent.com/6440523/50589026-bfd49d00-0e52-11e9-90ad-eb3c7094662c.png)

thanks!

**Comment by chunyenHuang** [comment]
Same issue with #67

**Comment by chunyenHuang** [comment]
Fix in `hummus-recipe@1.8.2`
