### ISSUE TITLE
Text fill color does not rotate with text

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#81]
When the fill color is provided to a text box, the fill rectangle has no mechanism to rotate, so it just sits there in 0 degree position while the text rotates out of the box.

**Comment by shaehn** [comment]
John,

I am able to rotate the fill color and the border box with the text, but I am having trouble with the rectangle positioning around the text. I am hoping you will be able to help me figure out what I need to do. The following picture shows 3 text boxes that obtain using fabricJS on an HTML canvas. The data from this is used to populate the PDF document that is to be generated. (Origin for text box is top,left, the rotation point however is the center of the text box) The control element in this experiment is the non-rotated box at the right.

![originalborders](https://user-images.githubusercontent.com/13596544/52972216-24f33c00-3388-11e9-9820-42cf407bfbcb.JPG)

The next picture shows the results after processing with hummus-recipe text API. 

![badborders](https://user-images.githubusercontent.com/13596544/52972386-bfec1600-3388-11e9-9260-c5acb61cf36c.JPG)

As you can see, the box outline gets positioned differently depending which direction the box was rotated.

The following is the code being used.  Since the rotation code in text.js seems to be working just fine, I packaged it up and put it in vector.helper.js because it is going to be called in 3  different places, once in text.js, and twice in the rectangle call in vector.js

```javascript
exports._setRotationContext = function _setRotationTransform(context, x, y, options) {

    if (options.rotation === void(0)) {
        context.cm(1, 0, 0, 1, x, y);    // no rotation
    } else {
        const rotationOrigin = (
            options.rotationOrigin &&
            Array.isArray(options.rotationOrigin) &&
            options.rotationOrigin.length == 2
        ) ? options.rotationOrigin : [options.originX, options.originY];

        const rm = getTransformParams(  // rotation matrix
            options.rotation, rotationOrigin[0], rotationOrigin[1], 
            x - rotationOrigin[0], y - rotationOrigin[1
        );

        context.cm(rm[0], rm[1], rm[2], rm[3], rm[4], rm[5]);
    }
}
```

This is the modified call to rectangle in text.js:

```javascript
if (textBox.style) {
        this.rectangle(
            nx,
            ny - textBox.height + textBox.firstLineHeight,
            textBox.width, textBox.height, Object.assign(textBox.style, {
                dontTranslate: true,
                rotation: pathOptions.rotation,              // new
                rotationOrigin: pathOptions.rotationOrigin, // new
                originX: pathOptions.originX,               // new
                originY: pathOptions.originY                // new
            })
        );
    }
```

Finally, my changes to the rectangle code in vector.js

```javascript
exports.rectangle = function rectangle(x, y, width, height, options = {}) {
    const {
        nx,
        ny
    } = (!options.dontTranslate) ? this._calibrateCoordinate(x, y, 0, -height): {
        nx: x,
        ny: y
    };

    if (!options.rotationOrigin) options.rotationOrigin = [nx, ny];
    if (options.fill || options.color) {
        const pathOptions = this._getPathOptions(options);
        pathOptions.type = 'fill';
        pathOptions.color = pathOptions.fill || pathOptions.color;

        this.pauseContext();
        const xObject = new xObjectForm(this.writer, width, height);
        xObject.getContentContext()
            .q()
            .gs(xObject.getGsName(pathOptions.fillGsId))
            .drawRectangle(0, 0, width, height, pathOptions)
            .Q();
        xObject.end();
        this.resumeContext();

        const context = this.pageContext;
        context.q();
        this._setRotationContext(context, nx, ny, options);
        context.doXObject(xObject)
            .Q();
    }

    if (options.stroke) {
        const pathOptions = this._getPathOptions(options);
        pathOptions.type = 'stroke';
        pathOptions.color = pathOptions.stroke || pathOptions.color;

        this.pauseContext();
        const xObject = new xObjectForm(this.writer, width, height);
        xObject.getContentContext()
            .q()
            .d(pathOptions.dash, pathOptions.dashPhase)
            .drawRectangle(0, 0, width, height, pathOptions)
            .Q();
        xObject.end();
        this.resumeContext();

        const context = this.pageContext;
        context.q();
        this._setRotationContext(context, nx, ny, options);
        context.doXObject(xObject)
            .Q();
    }

    return this;
};
```

Thanks for your help

**Comment by shaehn** [comment]
Never mind, I figured out what needs to be done.

**Comment by shaehn** [comment]
John, when I initiated a pull request, it said it could not automatically merge with your code. Do I go ahead and finish the pull request anyway?

**Comment by chunyenHuang** [comment]
You may need to merge or rebase onto the latest codes.

**Comment by shaehn** [comment]
I did the following:
git checkout master
git pull https://github.com/chunyenHuang/hummusRecipe.git master
Did a manual merge to the conflict, then pushed up to my fork.
I hope that is what works, I never understand the nuance of merge to latest or rebase.
