### ISSUE TITLE
Text truncation occurs in multiple line rotated text box

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#86]
On a rotated text box, when I enter a multiple line text with the text getting progressively smaller, the middle text gets truncated. In the picture below, the top box is not rotated. Text appears fine. The bottom box shows the truncation.

![texttruncation](https://user-images.githubusercontent.com/13596544/53049124-5d684800-3464-11e9-8337-053e523d8ec7.JPG)

I debugged the code and I know what is happening. The linewidth associations are incorrect. Line 3 is using the one from line 4; Line 2 is using the one from line 3.

Due the postponement of executing the writeText function by pushing state info on a stack, the writeText function is accessing the current global value. In actuality, the lineWidth & lineHeight should be part of that state information being used for later access.

The question I have, is how do you want this fixed?  Would it be alright to put lineHeight and lineWidth in the writeOptions object? If not, the writeText interface is going to have to change.

Current delaying code:

```javascript
        const startX = nx + currentLineWidth;
        if (text != '[@@DONOT_RENDER_THIS@@]') {
            toWriteContents.push({
                startX,
                text,
                writeOptions
            });
        }
```
Proposed delaying code
```javascript
        const startX = nx + currentLineWidth;
        if (text != '[@@DONOT_RENDER_THIS@@]') {
            toWriteContents.push({
                startX,
                toWriteTextObject   <- this holds all currently needed values
            });
        }
```
This only solves saving the current state values. I could add another parameter to writeText which would hold the saved state information. That way the options argument to writeText doesn't get polluted.
For example,

const writeText = (context, text, x, y, options, **state**)

Let me know how to proceed. Thanks.

**Comment by shaehn** [comment]
John, I have a fix for this problem, but I am having problems with dang github. I promoted my changes to my fork. Then I went to my fork and poked the new Pull Request button. It stated that the changes would merge automatically, but there is no other button to push to actually get the push to happen.

So at this point I am stuck and need a little help to see what I am doing wrong.

Thanks.

**Comment by shaehn** [comment]
Hmm.... Looking at the one pull request that I have in, it looks like the 2nd issue is included with the first. Is that how this is supposed to work? I thought that each issue would get its own pull request.

**Comment by chunyenHuang** [comment]
no worry, let's just reference the PR to the tickets.

**Comment by shaehn** [comment]
John, Is there something I still need to do, or will this change go into the next patch/release?

**Comment by chunyenHuang** [comment]
I have some modification and will work on it soon. sry for the wait.
