### ISSUE TITLE
merge problem with #81 causing fill position failure

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#90]
John,  Today I updated my work area with the 1.8.3 version of hummus-recipe so I could integrate it with my project and was dismayed that what I could have sworn was working properly when I checked it in, but now is not doing so well. The fill rectangle for text boxes is way outside the box.  I tracked down the culprit line inside vector.js

```javascript
        context.q();
        this._setRotationContext(context, nx, ny, options);
        context.cm(1, 0, 0, 1, nx, ny)   <-- BAD ONE
            .doXObject(xObject)
            .Q();
```

what it should look like is the following:

```javascript
       context.q();
        this._setRotationContext(context, nx, ny, options);
        context
            .doXObject(xObject)
            .Q();
```

So I am guessing some sort of merge mess up happened.
Is there a way to write a test for the code to pop out that kind of error?

**Comment by chunyenHuang** [comment]
You are correct 

https://github.com/chunyenHuang/hummusRecipe/blob/805e6ee1e3224ce5b593fe80bf5d9d1735218b5f/lib/vector.helper.js#L191
