### ISSUE TITLE
when fill or stroke color is set to black (0x000000), default 'blue' color used

### ISSUE THREAD

**Issue by shaehn** [chunyenHuang/hummusRecipe#92]
There is a programming idiom being used which fails when the stroke or fill colors of elements is set to the color black which evaluates to zero (0).  With options.fill and options.stroke set to '#000000' (black), calling the following function

```javascript
const pathOptions = this._getPathOptions(options);
```

sets both pathOptions.fill and pathOptions.stroke to the number 0 and pathOptions.color to the internal default (bright blue) color value.

Thus, the code cannot use the following program idiom:

```javascript
pathOptions.color = pathOptions.stroke || pathOptions.color;
pathOptions.color = pathOptions.fill   || pathOptions.color;
```
but rather must do this:

```javascript
 pathOptions.color = (pathOptions.stroke === undefined) ? pathOptions.color : pathOptions.stroke;
pathOptions.color  = (pathOptions.fill  ===  undefined) ? pathOptions.color : pathOptions.fill;
```

**Comment by chunyenHuang** [comment]
Update `1.8.5`
