### ISSUE TITLE
Render modified PDF without have to save it first

### ISSUE THREAD

**Issue by jimmy-insignia** [chunyenHuang/hummusRecipe#95]
I just want to know, can I render pdf after modified the pdf? since right now I'm using:
```const recipe = new HummusRecipe(body, output)```

body can be a buffer, but output is path that's means it will create pdf file. is there any way to return a buffer of the modified pdf? Thank you

**Comment by chunyenHuang** [comment]
https://github.com/chunyenHuang/hummusRecipe/blob/master/lib/Recipe.js#L240

You can pass in `output=null or undefined` and it should return you the buffer instead of saving to pdf.

**Comment by jimmy-insignia** [comment]
Oh okay I see that. great! Thank you :)

**Comment by biloo-dev** [comment]
Any example please
Tried it but the buffer doesn't return

this is my Code 
![ddssddss](https://user-images.githubusercontent.com/37638323/97163522-1413e400-1781-11eb-8b2a-60e6e2087629.png)

this is my result 
![1](https://user-images.githubusercontent.com/37638323/97163569-242bc380-1781-11eb-8440-a32ffabebf39.png)
